services:
  redis:
    image: redis:8.2-alpine
    container_name: redis
    restart: always
    env_file:
      - ./.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --save 60 1 --loglevel Debug
    networks:
      app_network:
        ipv4_address: 192.168.0.2
  
  redis-insight:
    image: redis/redisinsight:2.70
    container_name: redis-insight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/db
    networks:
      app_network:
        ipv4_address: 192.168.0.3

volumes:
  redis_data:
  redis_insight_data:

networks:
      app_network:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 192.168.0.0/24
              gateway: 192.168.0.1
